DROP TABLE IF EXISTS cards;

CREATE TABLE cards (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    year TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    card_number TEXT NOT NULL,
    name TEXT NOT NULL
);